# Project information
site_name: Kubelinux.io
site_url: https://kubelinux.io/
site_author: Kubelinux Team

# Repository
repo_name: kubelinux-io/kubelinux-io.github.io
repo_url: https://github.com/kubelinux-io/kubelinux-io.github.io

# Copyright
copyright: Copyright &copy; 2016 - 2024 Kubelinux Team

# Mkdocs Material Settings
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - content.action.edit
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking

# Mkdocs Settings
docs_dir: ../
site_dir: !ENV [RUNNER_TEMP, '/tmp/mkdocs']
edit_uri: edit/main/docs/
use_directory_urls: false
extra:
  version:
    provider: mike
plugins:
  - blog
  - meta
  - search
  - tags

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.caption
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - tables
  - toc:
      title: On this page
      permalink: true
