# Project information
site_name: Kubelinux.io
site_url: https://kubelinux.io
site_author: Kubelinux Team

# Repository
repo_name: kubelinux-io/kubelinux-io.github.io
repo_url: https://github.com/kubelinux-io/kubelinux-io.github.io

# Copyright
copyright: Copyright &copy; 2016 - 2024 Kubelinux Team

theme:
  name: material